spring:
  application:
    name: java-spring-boot-2025
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_spring_boot_2025?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
server:
  port: 9000
